version: '3'

services:
  stub:
    image: danielgtaylor/apisprout:latest
    ports:
      - '8000:8000'
    volumes:
      - ./openapi.yaml:/openapi.yaml
    entrypoint: /usr/local/bin/apisprout /openapi.yaml --watch
